### ISSUE TITLE
Hosts with trailing dot don't pass validation

### ISSUE THREAD

**Issue by trntv** [thephpleague/url#51]
Hi, first of all, thank your for your work.
There is a small problem - host with a trailing dot seems to be a valid host name, but such names don't pass `Host::isValidHostPattern` check. 
It throws an error, when using ’Url::createFromServer($_SERVER)’ with `$_SERVER['HTTP_HOST'] = example.com.`. This may happen if you don't filter such names on web server and someone make a request with `Host: example.com.` header.

Explanation why such names are valid:
http://www.dns-sd.org/trailingdotsindomainnames.html

**Comment by nyamsprod** [comment]
This issue is resolved in upcoming v4. please refer to the master branch for test
