### ISSUE TITLE
Consider implementing RFC 3986 reference resolution

### ISSUE THREAD

**Issue by philjohn** [thephpleague/url#52]
As per: http://www.ietf.org/rfc/rfc3986.txt, section 5

This allows you to take one or more relative URIs and compute an absolute URI based on the algorithm contained in the RFC.

Useful when working with XML, HTML and RDF data formats.

I've got some code that implements this, but it's proprietary, so would need to get the OK from work to do a pull request.

**Comment by nyamsprod** [comment]
thanks, for the suggestion and it's already in the road map for v4. But a pull request with an implementation would be great

**Comment by nyamsprod** [comment]
reference resolution has been added to the dev-master it will be available in version 4
