### ISSUE TITLE
Leading slash in path

### ISSUE THREAD

**Issue by tim-bezhashvyly** [thephpleague/url#53]
Any reason why `\League\Url\Components\Path::getUriComponent` adds leading slash to path? And if there is one maybe it will make sense to use `\League\Url\Components\Path::$delimiter` property for this purpose?

**Comment by nyamsprod** [comment]
Hi,
as per the [documentation](http://url.thephpleague.com/3.0/components/overview/#component-interface)  `getUriComponent()`: returns an altered string representation to ease URL representation. 

Please refer to the documentation as everything is explained there.
