### ISSUE TITLE
Export to array

### ISSUE THREAD

**Issue by web777** [thephpleague/url#56]
Please do export to array all information from components.
I need it for json presentation in my service.
```
$url =  \League\Url\Url::createFromUrl('http://url.com/param1=val1&param2=val2');
$array = $url->toArray();
var_export($array);
```
and get 
```
[
    'host' => 'url.com',
    'query' => [
         'param1' => 'val1',
         'param2' => 'val2',
    ]
...
]



```

**Comment by nyamsprod** [comment]
this enhancement is already scheduled for v4

**Comment by web777** [comment]
Well, I will use purl from @jwage before you release.

**Comment by nyamsprod** [comment]
A new version 3.3 is out with the toArray method added to the URL class

**Comment by web777** [comment]
Awesome!
