### ISSUE TITLE
Code is overly restrictive

### ISSUE THREAD

**Issue by shadowhand** [thephpleague/url#60]
The usage of `private` and `final` violates the [Open/Closed Principle](https://en.wikipedia.org/wiki/Open/closed_principle) by preventing extension without modification. See also the [Liskov Substitution Principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle), as a `final` class cannot be replaced without re-implementing the logic of that class.

**Comment by nyamsprod** [comment]
Yep, This has been corrected in a new draft version which follow the roadmap in #57. The update will be reflected on a future commit to github

**Comment by nyamsprod** [comment]
the code is master has been updated and this issue is resolved
