### ISSUE TITLE
Issue with example.org:80 depends on the OS

### ISSUE THREAD

**Issue by stepanselyuk** [thephpleague/url#65]
Hello,
one of the test failing and I tried to figure out what's happened.

This is simplified code:
```php
try {
            $url = LeagueUrl::createFromUrl('example.org:80');
        } catch (\Exception $e) {
            return false;
        }
```
It is parsing OK in CentOS and OSX, but throw exception in Ubuntu and Windows:

```bash
# in CentOS:
php -r 'var_export(parse_url("//example.org:80"));'
array (
  'host' => 'example.org',
  'port' => 80,
)

#in Ubuntu:
php -r 'var_export(parse_url("//example.org:80"));'
false
```

**Comment by nyamsprod** [comment]
Hi @stepanselyuk,
Can you provide me more informations like the PHP version you are using.

**Comment by stepanselyuk** [comment]
Hi,
in CentOS:
```
php -v
PHP 5.5.24 (cli) (built: Apr 15 2015 17:36:46) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
```
in Ubuntu:
```
php -v
PHP 5.5.9-1ubuntu4.6 (cli) (built: Feb 13 2015 19:17:11) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```

**Comment by nyamsprod** [comment]
I think this is a bug in PHP parse_url function which is not fix il all versions... 
http://3v4l.org/pXelf

**Comment by stepanselyuk** [comment]
Thanks! Very helpful, especially http://3v4l.org :)

**Comment by nyamsprod** [comment]
So as recommend in the documentation you should use the latest stable version of PHP in 5.5 or 5.6 series where the bug is corrected. I will document it but I can not fix this bug in the library (v3 or v4 for that matter) since the library depends on PHP `parse_url`

**Comment by stepanselyuk** [comment]
Actually you can know if bugged version of PHP used by 
```php
if ( @parse_url("//example.org:80") === false ) { ... }
```
Then may be doing some fallback after check the URL by simple regexp like:

```php
preg_match('/\/\/#domain_name_check_with_idn_support_here#:\d+/', $url)
```

**Comment by stepanselyuk** [comment]
or 
```php
if(strpos($url, '/')===0 && @parse_url($url) === false && ($_=@parse_url('http:'.$url)) !== false) {
// php bug detected,
// parse with http prefix
// remove protocol item from $_
}
```

**Comment by nyamsprod** [comment]
You may submit a PR with your intended solution but I'm a bit hesitant in using this kind of patch. League\Url v3 is filled with these kind of patch and while they appear to solve edge cases they end up adding more bugs.

**Comment by stepanselyuk** [comment]
Hi, 
Ok I created the PR.

**Comment by stepanselyuk** [comment]
I created PR for v3 (fix+test), but about test, it is also depends on `parse_url` implementation.

**Comment by nyamsprod** [comment]
Ok I'll review it tonight or tomorrow if all is good I'll make a patch release this week if I stil can :+1:

**Comment by nyamsprod** [comment]
the issue is resolved.. a patch release for v3 will be out

**Comment by stepanselyuk** [comment]
Thanks!

**Comment by nyamsprod** [comment]
version 3.3.2 is out with your bug fix thanks for your help :+1:
