### ISSUE TITLE
Removing extension

### ISSUE THREAD

**Issue by akohutovic** [thephpleague/url#69]
I did not find a method for removing the extension from the path.
Setting `->withExtension(null)` will produce tailing '.' in the result.

**Comment by nyamsprod** [comment]
@akohutovic Hi,

Are you already using v4 ? If so:

- a patch version with the fix is on its way
- do you like/dislike the new API? What is your opinion... your feedback are more than welcomed

**Comment by akohutovic** [comment]
Hmm, I am not completely happy that everytime I aske for a component it's a clone so I have to re-assing it back to the original object.
Is there way to change e.g. Query *in situ*?

**Comment by nyamsprod** [comment]
The documentation for query is quite finish thought you may have a look at it:
http://url.thephpleague.com/dev-master/components/query/

**Comment by nyamsprod** [comment]
bug fixed in the latest master commit

**Comment by nyamsprod** [comment]
@akohutovic I've updated v4 with a [League\Url\Services\Builder](http://url.thephpleague.com/dev-master/services/builder/) class that should help you manipulating the URL more easily.
Be aware that v4 is still not in feature freeze. The changes were made after your comments and to be more PSR-7 compliant. Hope you like them.
