### ISSUE TITLE
Nested array in query parsed wrong

### ISSUE THREAD

**Issue by velosipedist** [thephpleague/url#70]
From query string `filter[key1][]=1&filter[key1][]=2` i expect to get
```php
[
  'filter' => [1,2]
]
```

But i got
```php
[
  'filter' => 2
]
```

What is purpose of replacements done [here](https://github.com/thephpleague/url/blob/master/src/Query.php#L95)?

Simple call of `parse_str()` does job well.

**Comment by nyamsprod** [comment]
@velosipedist ,

Hi, I can't seem to reproduce the error. Can you provide me with a complete test code and the PHP version you are using please.

**Comment by velosipedist** [comment]
ok, i'll esnd it next day

**Comment by nyamsprod** [comment]
This issue is resolved in v4
