### ISSUE TITLE
Undefined offset: 0 in Punycode.php:102

### ISSUE THREAD

**Issue by darkunz** [thephpleague/url#73]
this invalid idn `'http://xn--fsqu00a.xn--g6w131251d/` produce this error

```
PHP Notice 'ErrorException' with message 'Undefined offset: 0'
in /vendor/league/url/src/Utilities/Punycode.php:102
```

**Comment by nyamsprod** [comment]
@darkunz Thanks for reporting this issue. I've updated IDN handling in the package to resolve the reported. Please feel free to try the master branch. To see for yourself.
