### ISSUE TITLE
[Question] Any way to change query params of an existing Url object?

### ISSUE THREAD

**Issue by ArtemGordinsky** [thephpleague/url#78]
I've been playing around with 4.0.3 today, and I wasn't able to find a way to accomplish the following:

1.  Create a url from string (e.g. ```http://github.com/thephpleague?a=1```);
2.  Merge its query params with an array of different params (e.g. ```['foo' => 'bar', 'bar' => 'foo']```);
3. Return a full string with all of the query params (e.g. ```http://github.com/thephpleague?a=1&foo=bar&bar=foo```);

The query appears to be immutable. Is this the intended behaviour? Am I missing something? I hope someone could help me understand.

P.S. Thanks for a great component!

**Comment by nyamsprod** [comment]
This is really simple :)
```php
<?php

use League\Url\Url;

$url = Url::createFromUrl("http://github.com/thephpleague?a=1");
$newUrl = $url->mergeQuery(['foo' => 'bar', 'bar' => 'foo']);
echo $newUrl; // returns http://github.com/thephpleague?a=1&foo=bar&bar=foo
````
You should read this documentation page about [partially updating the URL](http://url.thephpleague.com/4.0/url/manipulation/#partial-url-components-modifications). 

About Immutability: In v4 all URL related classes are immutable. This is also explained in [the documentation](http://url.thephpleague.com/4.0/definitions/)

**Of note:** If your are using the 4.0.0.Beta3, the SchemeRegistry does not exist yet. It will ship with the final version

Hope this answer your question :+1:

**Comment by ArtemGordinsky** [comment]
Thanks, it totally does!
My bad missing that section in the manual. Keep up the good job :+1:
